### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by dayed** [misterion/ko-process#13]
PHP Fatal error:  Call to undefined function Ko\shm_attach() in /Paidata/www/process/vendor/misterion/ko-process/src/Ko/SharedMemory.php on line 83

Fatal error: Call to undefined function Ko\shm_attach() in /Paidata/www/process/vendor/misterion/ko-process/src/Ko/SharedMemory.php on line 83

**Comment by misterion** [comment]
Is `sysvshm` enabled in your php installation? You may find notes about `sysvshm` installation in http://php.net/manual/en/sem.installation.php
