### ISSUE TITLE
Unclean code

### ISSUE THREAD

**Issue by p-golovin** [misterion/ko-process#14]
/**
     * Return count of currently running child process.
     *
     * @return int
     */
    public function getProcessCount()
    {
        return count($this);
    }
    /**
     * Return count of currently running child process.
     *
     * @return int
     */
    public function count()
    {
        return count($this->children);
    }

Should be in first function?
return $this->count($this);

**Comment by misterion** [comment]
Yes, it's unclean. Both `getProcessCount` and `count` should return count($this->children). Send pull request if you wish!
