### ISSUE TITLE
Share Memory Requirement

### ISSUE THREAD

**Issue by shanehandley** [misterion/ko-process#18]
Hi, the composer packages suggests ext-sysvshm, but is this actually a requires? Without ext-sysvshm installed executing code from 'Usage' in README.md fails with an fatal error:

`PHP Fatal error:  Call to undefined function Ko\shm_attach() in /srv/movember.com/releases/20120817072736/vendor/misterion/ko-process/src/Ko/SharedMemory.php on line 83`

Thanks.

**Comment by misterion** [comment]
Hi, 
This extension should be enabled with recompiling your php (or enable it it ini file if already have it). It can`t be installer with composer, so the requires just indicates is your installation can be used.
To enable System V semaphore support compile PHP with the option `--enable-sysvsem`. To enable the System V shared memory support compile PHP with the option `--enable-sysvshm`. 
You may find more info in http://php.net/manual/en/sem.installation.php

**Comment by shanehandley** [comment]
Thanks misterion, it works great with sysvsem and sysvshm enabled. I was just a little confused as to whether I could get it working without them, but I understand composer does not have fields for required PHP extensions. Thanks again.
