### ISSUE TITLE
SIGTERM and SIGINT handling

### ISSUE THREAD

**Issue by umpirsky** [misterion/ko-process#21]
I am trying to get advantage of `onShutdown` handler:

```php
$processManager = new Ko\ProcessManager()
$processManager->fork(function(Process $process) {
});

$processManager->fork(function(Process $process) {
});

$processManager->onShutdown(function () {
    echo 'Shutting down';
});

$processManager->wait();
```

But it is never called. 

When I interrupt my script with `Ctrl + C` `SIGINT` signal is sent.

`SIGTERM` is expected in:

```php
protected function setupSignalHandlers()
{
    $this->signalHandler = new SignalHandler();
    $this->signalHandler->registerHandler(SIGCHLD, function() {
        $this->handleSigChild();
    });

    $this->signalHandler->registerHandler(SIGTERM, function() {
        $this->handleSigTerm();
    });
}
```

I have tried adding:

```
$this->signalHandler->registerHandler(SIGINT, function() {
    $this->handleSigTerm();
});
```

But then the script is never interrupted.

**Comment by misterion** [comment]
Look's like joke but this is normail is php application then tru to catch SIGTERM  from console. Here is good explanation why this so http://www.hackingwithphp.com/16/1/1/taking-control-of-php. You can catch SIGTERM request with `kill <pid>` for your master/slave php process.

**Comment by umpirsky** [comment]
@misterion Thanks.

But, shouldn't we trigger `onShutdown` on `SIGINT`?

**Comment by misterion** [comment]
Only if send it with kill

**Comment by umpirsky** [comment]
OK, maybe it wold be useful to have something for SIGINT, maybe new method like:

```php
$processManager->onInterrupt(function () {
    // 
});
```

**Comment by misterion** [comment]
But php actually can not hande SIGINT/SIGTERM sended from console.
