### ISSUE TITLE
Please bump tag on Packagist

### ISSUE THREAD

**Issue by ovr** [misterion/ko-process#23]
Hey!

https://packagist.org/packages/misterion/ko-process
![image](https://cloud.githubusercontent.com/assets/572096/14379058/cc8ffdfe-fd80-11e5-9162-8134c2e46347.png)
I need `0.5.3`

Or use auto hook, settings -> web service (hooks) -> add service -> packagist

Thanks :cake:

**Comment by misterion** [comment]
It`s already done via hooks. Looks like something wrong with packagist. Update it by hands.

**Comment by ovr** [comment]
@misterion Thank you!
